// weapons
scriptEvent float getAux();
scriptEvent void setAux(float aux);
scriptEvent void beginLightSync();
scriptEvent void setNetfiring(float isNetfiring);
scriptEvent void setWeaponGuiParm(string key, string value);
scriptEvent	void fireWeaponBegin();
scriptEvent	void fireWeaponEnd();

// monsters
scriptEvent void cclearGrabbed();
scriptEvent entity findHittableEnemy(float useFov);
scriptEvent entity findHittableEnemyAI(float useFov);
scriptEvent	void gib( string damage_def ); 

// players
scriptEvent void Damage(string damageDef);
