/***********************************************************************

weapon_flashlight.script

***********************************************************************/

// blend times
#define FLASHLIGHT_IDLE_TO_LOWER	4
#define FLASHLIGHT_IDLE_TO_FIRE		2
#define	FLASHLIGHT_IDLE_TO_RELOAD	4
#define FLASHLIGHT_RAISE_TO_IDLE	4
#define FLASHLIGHT_FIRE_TO_IDLE		4
#define FLASHLIGHT_RELOAD_TO_IDLE	4

object weapon_flashlight : weapon_base_flashlight {
	float		netFired;

	string		skin_on;
	string		skin_on_invis;
	string		skin_off;
	string		skin_off_invis;

	void		init();

	void		Lower();
	void		Raise();
	void		Idle();
	void		Fire();
	void		ToggleOnOff();
	void		EnterCinematic();
	void		ExitCinematic();
	void		NetCatchup();

				// called by the game
	void		UpdateSkin();
};

void weapon_flashlight::init() {
	netFired = false;

	skin_on			= getKey( "skin_on" );
	skin_on_invis	= getKey( "skin_on_invis" );
	skin_off		= getKey( "skin_off" );
	skin_off_invis	= getKey( "skin_off_invis" );

	weaponState( "Raise", 0 );
}

void weapon_flashlight::Raise() {
	weaponRising();
	playAnim( ANIMCHANNEL_ALL, "raise" );
	SetLight( !getIntKey( "start_off" ) );
	while( !animDone( ANIMCHANNEL_ALL, FLASHLIGHT_RAISE_TO_IDLE ) ) {
		updateLightIntensity();
		waitFrame();
	}

	beginLightSync();

	weaponState( "Idle", FLASHLIGHT_RAISE_TO_IDLE );
}

void weapon_flashlight::NetCatchup() {
	SetLight( !getIntKey( "start_off" ) );
	beginLightSync();
	weaponState( "Idle", 0 );
}

void weapon_flashlight::Lower() {
	weaponLowering();
	playAnim( ANIMCHANNEL_ALL, "putaway" );
	waitUntil( animDone( ANIMCHANNEL_ALL, 0 ) );
	weaponHolstered();
	while( !WEAPON_RAISEWEAPON ) {
		updateLightIntensity();
		waitFrame();
	}
	weaponState( "Raise", 0 );
}

void weapon_flashlight::Idle() {
	weaponReady();
	playCycle( ANIMCHANNEL_ALL, "idle" );
	while( 1 ) {
		updateLightIntensity();
		if ( WEAPON_LOWERWEAPON ) {
			weaponState( "Lower", FLASHLIGHT_IDLE_TO_LOWER );
		}

		if ( WEAPON_ATTACK || WEAPON_NETFIRING ) {
			netFired = WEAPON_NETFIRING;
			setNetfiring(true);
			weaponState( "Fire", FLASHLIGHT_IDLE_TO_FIRE );
		}
		if ( WEAPON_RELOAD ) {
			weaponState( "ToggleOnOff", FLASHLIGHT_IDLE_TO_RELOAD );
		}
		waitFrame();
	}
}

void weapon_flashlight::Fire() {
	float waitTime;

	if ( !sys.isMultiplayer() ) {
		do {
			playAnim( ANIMCHANNEL_ALL, "fire" );
			waitTime = sys.getTime() + 0.1;
			while( sys.getTime() < waitTime ) {
				updateLightIntensity();
				waitFrame();
			}
			melee();
			while( !animDone( ANIMCHANNEL_ALL, FLASHLIGHT_FIRE_TO_IDLE ) ) {
				updateLightIntensity();
				waitFrame();
			}
		} while ( WEAPON_ATTACK || WEAPON_NETFIRING );
	} else {
		float doBreak = false;
		do {
			playAnim( ANIMCHANNEL_ALL, "fire" );
			waitTime = sys.getTime() + 0.1;
			while( sys.getTime() < waitTime ) {
				updateLightIntensity();
				waitFrame();
			}
			melee();

			while( !animDone( ANIMCHANNEL_ALL, FLASHLIGHT_FIRE_TO_IDLE + 5 ) ) {
				updateLightIntensity();
				waitFrame();
			}
			if ( !netFired && (!WEAPON_ATTACK || WEAPON_LOWERWEAPON) ) {
				doBreak = true;
				setNetfiring(false);
			}

			while( !animDone( ANIMCHANNEL_ALL, FLASHLIGHT_FIRE_TO_IDLE ) ) {
				updateLightIntensity();
				waitFrame();
			}
		} while ( (!netFired && !doBreak) || (netFired && WEAPON_NETFIRING) );
	}

	weaponState( "Idle", FLASHLIGHT_FIRE_TO_IDLE );
}

void weapon_flashlight::ToggleOnOff() {
	float waitTime;

	playAnim( ANIMCHANNEL_ALL, "reload" );

	waitTime = sys.getTime() + 0.2;
	while( sys.getTime() < waitTime ) {
		updateLightIntensity();
		waitFrame();
	}

	SetLight( !on );

	while( !animDone( ANIMCHANNEL_ALL, FLASHLIGHT_RELOAD_TO_IDLE ) ) {
		updateLightIntensity();
		waitFrame();
	}

	weaponState( "Idle", FLASHLIGHT_RELOAD_TO_IDLE );
}

void weapon_flashlight::EnterCinematic() {
	onBeforeCinematic = on;
	SetLight( false );
	weaponState( "Idle", 0 );
}

void weapon_flashlight::ExitCinematic() {
	netFired = false;
	SetLight( onBeforeCinematic );
	intensity = 1.0;
	updateLightIntensity();
	weaponState( "Idle", 0 );
}

void weapon_flashlight::UpdateSkin() {
	if ( on && ( global_flashlight_intensity > 0 ) ) {
		if ( !isInvisible() ) {
			setSkin( skin_on );
		} else {
			setSkin( skin_on_invis );
		}
	} else {
		if ( !isInvisible() ) {
			setSkin( skin_off );
		} else {
			setSkin( skin_off_invis );
		}
	}
}
